# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'StateMod (Develop)'
nav:
- 'Introduction': index.md
- 'New Developer Setup':
  - 'Overview': dev-new/overview.md
- 'Development Tasks':
  - 'Overview': dev-tasks/overview.md
  - 'Linux Commands': dev-tasks/linux-commands.md
  - 'Run Eclipse': dev-tasks/run-eclipse.md
  - 'Designing Software': dev-tasks/designing-software.md
  - 'Version Control with Git': dev-tasks/versioning.md
  - 'Documenting': dev-tasks/documenting.md
  - 'Troubleshooting Eclipse': dev-tasks/troubleshooting-eclipse.md
  - 'Coding': dev-tasks/coding.md
  - 'Compiling': dev-tasks/compiling.md
  - 'Testing': dev-tasks/testing.md
  - 'Releasing': dev-tasks/releasing.md
  - 'FAQ for Cygwin': dev-tasks/faq-cygwin.md
  - 'FAQ for Linux': dev-tasks/faq-linux.md
  - 'FAQ for MinGW': dev-tasks/faq-mingw.md
- 'Code List': code-list/code-list.md
- 'Resources': resources/resources.md
- 'REFERENCE: Software Design':
  - 'Overview': software-design/overview.md
- 'REFERENCE: Deployed Environment':
  - 'Overview': deployed-env/overview.md
- 'REFERENCE: Development Environment':
  - 'Overview': dev-env/overview.md
  - 'Machine': dev-env/machine.md
  - 'Git': dev-env/git.md
  - 'Python and pip': dev-env/python.md
  - 'pytest': dev-env/pytest.md
  - 'MkDocs': dev-env/mkdocs.md
  - 'Java 8': dev-env/java8.md
  - 'gfortran': dev-env/gfortran.md
  - 'Eclipse and Photran': dev-env/eclipse.md
  - 'Text Editor': dev-env/text-editor.md
  - 'Doxygen': dev-env/doxygen.md
  - 'KDiff3': dev-env/kdiff3.md
- 'REFERENCE: Initial Project Setup':
  - Overview: project-init/overview.md
  - 'Create Development Home Folder': project-init/home-folder.md
  - 'GitHub Git Repository': project-init/github.md
  - 'Eclipse Run Script': project-init/eclipse-run-script.md
  - 'Eclipse Workspace': project-init/eclipse-workspace.md
  - 'Eclipse StateMod Project': project-init/eclipse-statemod-project.md
  - 'Eclipse Folder Structure': project-init/eclipse-folder-structure.md
  - 'Eclipse Make Targets': project-init/eclipse-make-targets.md
  - 'Build Utility Scripts': project-init/build-util.md
  - 'Documentation, Legacy  (Word)': project-init/doc.md
  - 'Documentation, Developer (MkDocs)': project-init/doc-dev.md
  - 'Documentation, User (MkDocs)': project-init/doc-user.md
  - 'Documentation, API (Doxygen)': project-init/doc-doxygen.md
  - 'Git StateMod History': project-init/git-statemod-history.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'CO Department of Natural Resources'
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
 - 'UA-43023264-1'
 - auto
# ------------------------------------------------
# Don't publish the repo because it leads to irritating edit links
#repo_url:  https://github.com/OpenCDSS/cdss-app-statemod-fortran-doc-dev
# ------------------------------------------------
site_author: 'CO Department of Natural Resources'
site_description:  'CDSS StateMod Documentation (Develop)'
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon: 'images/NewCOLogo32x32.gif'
